version: '3'
services:
  graph-node:
    image: graphprotocol/graph-node:v0.24.2
    ports:
      - '8000:8000'
      - '8001:8001'
      - '8020:8020'
      - '8030:8030'
      - '8040:8040'
    depends_on:
      - ipfs
      - postgres
    networks:
      - default
    environment:
      postgres_host: postgres
      postgres_user: <postgres_user>
      postgres_pass: <postgres_password>
      postgres_db: graph-node
      ipfs: 'ipfs:5001'
      ethereum: 'mainnet:https://rpc1.piccadilly.autonity.org/'
      GRAPH_LOG: info
  ipfs:
    image: ipfs/kubo:v0.14.0
    ports:
      - '5001:5001'
    volumes:
      - ./data/ipfs:/data/ipfs
  postgres:
    image: postgres:14
    # ports:
    #   - '5432:5432'
    command:
      [
        "postgres",
        "-cshared_preload_libraries=pg_stat_statements",
        "-cmax_connections=200"
      ]
    environment:
      POSTGRES_USER: <postgres_user>
      POSTGRES_PASSWORD: <postgres_password>
      POSTGRES_DB: graph-node
      PGDATA: "/var/lib/postgresql/data"
      POSTGRES_INITDB_ARGS: "-E UTF8 --locale=C"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  webclient-uniswap:
    image: <webclient_image_url>
    ports:
      - "8012:3000"
  pluto-landing:
    image: <pluto_landing_image_url>
    ports:
      - '8011:3000'